import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProfileEntities1769160948978 implements MigrationInterface {
    name = 'AddProfileEntities1769160948978'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` DROP FOREIGN KEY \`verification_tokens_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` DROP FOREIGN KEY \`refresh_tokens_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`password_history\` DROP FOREIGN KEY \`password_history_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`user_roles_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`user_roles_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`name\` ON \`roles\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`username\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_expires_at\` ON \`verification_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_token\` ON \`verification_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_type\` ON \`verification_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_user_id\` ON \`verification_tokens\``);
        await queryRunner.query(`DROP INDEX \`token\` ON \`verification_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_expires_at\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_token\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_user_id\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_created_at\` ON \`password_history\``);
        await queryRunner.query(`DROP INDEX \`idx_user_id\` ON \`password_history\``);
        await queryRunner.query(`DROP INDEX \`role_id\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`unique_user_role\` ON \`user_roles\``);
        await queryRunner.query(`CREATE TABLE \`provider_profiles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`user_id\` int NOT NULL, \`name\` varchar(100) NOT NULL, \`phone\` varchar(15) NULL, \`photo_url\` varchar(500) NULL, \`location\` varchar(255) NOT NULL, \`latitude\` decimal(10,7) NULL, \`longitude\` decimal(10,7) NULL, \`languages\` text NULL, \`availability\` text NULL, \`profile_status\` varchar(255) NOT NULL DEFAULT 'draft', \`is_premium\` tinyint NOT NULL DEFAULT 0, \`provider_status\` varchar(255) NOT NULL DEFAULT 'offline', \`rating\` decimal(3,2) NULL DEFAULT '0.00', \`reviews_count\` int NOT NULL DEFAULT '0', \`completed_bookings\` int NOT NULL DEFAULT '0', \`verifications\` text NULL, \`badges\` text NULL, UNIQUE INDEX \`IDX_5d1880ed16ff13ea6fd9bca019\` (\`user_id\`), UNIQUE INDEX \`REL_5d1880ed16ff13ea6fd9bca019\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`certificates\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`service_config_id\` int NOT NULL, \`name\` varchar(100) NOT NULL, \`contact_info\` varchar(255) NULL, \`description\` text NOT NULL, \`certificate_type\` varchar(255) NOT NULL, \`file_name\` varchar(255) NULL, \`file_url\` varchar(500) NULL, \`verification_status\` varchar(255) NOT NULL DEFAULT 'pending', \`verified_at\` timestamp NULL, \`verified_by\` int NULL, \`rejection_reason\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`service_configs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`provider_id\` int NOT NULL, \`care_category\` varchar(255) NOT NULL, \`completed\` tinyint NOT NULL DEFAULT 0, \`tasks\` text NULL, \`hourly_rate\` decimal(10,2) NOT NULL DEFAULT '0.00', \`shift_rate\` decimal(10,2) NULL, \`urgent_surcharge\` decimal(5,2) NULL, \`description\` text NULL, \`experience\` varchar(50) NULL, \`availability\` text NULL, \`schedule_start\` time NULL, \`schedule_end\` time NULL, \`specific_dates\` text NULL, \`training\` text NULL, \`medical_skills\` text NULL, \`accepted_pets\` text NULL, \`pet_work_zones\` text NULL, \`max_pets\` int NULL, \`cleaning_products\` varchar(255) NULL, \`has_equipment\` tinyint NOT NULL DEFAULT 0, \`waste_management\` tinyint NOT NULL DEFAULT 0, \`eco_friendly\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`service_variations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`service_config_id\` int NOT NULL, \`name\` varchar(100) NOT NULL, \`price\` decimal(10,2) NOT NULL, \`unit\` varchar(50) NOT NULL, \`enabled\` tinyint NOT NULL DEFAULT 1, \`description\` text NULL, \`is_custom\` tinyint NOT NULL DEFAULT 0, \`display_order\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`login_attempts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`identifier\` varchar(100) NOT NULL, \`ip_address\` varchar(45) NOT NULL, \`user_agent\` text NULL, \`is_successful\` tinyint NOT NULL DEFAULT 0, \`failure_reason\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`blocked_until\` datetime NULL, INDEX \`idx_identifier_created\` (\`identifier\`, \`created_at\`), INDEX \`idx_ip_created\` (\`ip_address\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`client_profiles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`user_id\` int NOT NULL, \`name\` varchar(100) NOT NULL, \`phone\` varchar(15) NULL, \`photo_url\` varchar(500) NULL, \`location\` varchar(255) NOT NULL, \`latitude\` decimal(10,7) NULL, \`longitude\` decimal(10,7) NULL, \`languages\` text NULL, \`preferences\` text NULL, \`profile_status\` varchar(255) NOT NULL DEFAULT 'draft', \`is_premium\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_542bfcd136b7ef76af7e4edf1d\` (\`user_id\`), UNIQUE INDEX \`REL_542bfcd136b7ef76af7e4edf1d\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`assigned_at\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`user_id\`, \`role_id\`)`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email_verified\` \`email_verified\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` CHANGE \`token\` \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` ADD UNIQUE INDEX \`IDX_b00b1be0e5a820594d7c07a3df\` (\`token\`)`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` CHANGE \`is_used\` \`is_used\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` CHANGE \`is_revoked\` \`is_revoked\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`CREATE INDEX \`IDX_87b8888186ca9769c960e92687\` ON \`user_roles\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b23c65e50a758245a33ee35fda\` ON \`user_roles\` (\`role_id\`)`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` ADD CONSTRAINT \`FK_31d2079dc4079b80517d31cf4f2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`provider_profiles\` ADD CONSTRAINT \`FK_5d1880ed16ff13ea6fd9bca019d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`certificates\` ADD CONSTRAINT \`FK_aea86c98dd94cb703d6dea5880b\` FOREIGN KEY (\`service_config_id\`) REFERENCES \`service_configs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_configs\` ADD CONSTRAINT \`FK_249dddf0682f7c3009890ea20e8\` FOREIGN KEY (\`provider_id\`) REFERENCES \`provider_profiles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_variations\` ADD CONSTRAINT \`FK_0db0fedcca620058a3457533e4c\` FOREIGN KEY (\`service_config_id\`) REFERENCES \`service_configs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` ADD CONSTRAINT \`FK_3ddc983c5f7bcf132fd8732c3f4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_history\` ADD CONSTRAINT \`FK_4933dc7a01356ac0733a5ad52d9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`client_profiles\` ADD CONSTRAINT \`FK_542bfcd136b7ef76af7e4edf1d7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_87b8888186ca9769c960e926870\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_b23c65e50a758245a33ee35fda1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_b23c65e50a758245a33ee35fda1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_87b8888186ca9769c960e926870\``);
        await queryRunner.query(`ALTER TABLE \`client_profiles\` DROP FOREIGN KEY \`FK_542bfcd136b7ef76af7e4edf1d7\``);
        await queryRunner.query(`ALTER TABLE \`password_history\` DROP FOREIGN KEY \`FK_4933dc7a01356ac0733a5ad52d9\``);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` DROP FOREIGN KEY \`FK_3ddc983c5f7bcf132fd8732c3f4\``);
        await queryRunner.query(`ALTER TABLE \`service_variations\` DROP FOREIGN KEY \`FK_0db0fedcca620058a3457533e4c\``);
        await queryRunner.query(`ALTER TABLE \`service_configs\` DROP FOREIGN KEY \`FK_249dddf0682f7c3009890ea20e8\``);
        await queryRunner.query(`ALTER TABLE \`certificates\` DROP FOREIGN KEY \`FK_aea86c98dd94cb703d6dea5880b\``);
        await queryRunner.query(`ALTER TABLE \`provider_profiles\` DROP FOREIGN KEY \`FK_5d1880ed16ff13ea6fd9bca019d\``);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` DROP FOREIGN KEY \`FK_31d2079dc4079b80517d31cf4f2\``);
        await queryRunner.query(`DROP INDEX \`IDX_b23c65e50a758245a33ee35fda\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_87b8888186ca9769c960e92687\` ON \`user_roles\``);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` CHANGE \`is_revoked\` \`is_revoked\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` CHANGE \`is_used\` \`is_used\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` DROP INDEX \`IDX_b00b1be0e5a820594d7c07a3df\``);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` CHANGE \`token\` \`token\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email_verified\` \`email_verified\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`is_active\` \`is_active\` tinyint(1) NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`assigned_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX \`REL_542bfcd136b7ef76af7e4edf1d\` ON \`client_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_542bfcd136b7ef76af7e4edf1d\` ON \`client_profiles\``);
        await queryRunner.query(`DROP TABLE \`client_profiles\``);
        await queryRunner.query(`DROP INDEX \`idx_ip_created\` ON \`login_attempts\``);
        await queryRunner.query(`DROP INDEX \`idx_identifier_created\` ON \`login_attempts\``);
        await queryRunner.query(`DROP TABLE \`login_attempts\``);
        await queryRunner.query(`DROP TABLE \`service_variations\``);
        await queryRunner.query(`DROP TABLE \`service_configs\``);
        await queryRunner.query(`DROP TABLE \`certificates\``);
        await queryRunner.query(`DROP INDEX \`REL_5d1880ed16ff13ea6fd9bca019\` ON \`provider_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d1880ed16ff13ea6fd9bca019\` ON \`provider_profiles\``);
        await queryRunner.query(`DROP TABLE \`provider_profiles\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_user_role\` ON \`user_roles\` (\`user_id\`, \`role_id\`)`);
        await queryRunner.query(`CREATE INDEX \`role_id\` ON \`user_roles\` (\`role_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_id\` ON \`password_history\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_created_at\` ON \`password_history\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_id\` ON \`refresh_tokens\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_token\` ON \`refresh_tokens\` (\`token\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_expires_at\` ON \`refresh_tokens\` (\`expires_at\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`token\` ON \`verification_tokens\` (\`token\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_id\` ON \`verification_tokens\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_type\` ON \`verification_tokens\` (\`type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_token\` ON \`verification_tokens\` (\`token\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_expires_at\` ON \`verification_tokens\` (\`expires_at\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`username\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`name\` ON \`roles\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`user_roles_ibfk_2\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`user_roles_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_history\` ADD CONSTRAINT \`password_history_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` ADD CONSTRAINT \`refresh_tokens_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`verification_tokens\` ADD CONSTRAINT \`verification_tokens_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
